@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun May 25 15:46:33 +0700 2025
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim ASIP_one_one_tb_behav -key {Behavioral:sim_1:Functional:ASIP_one_one_tb} -tclbatch ASIP_one_one_tb.tcl -view E:/codeDSIP_DoAn1/150425/Hardware_ASIP_14042025/Hardware_ASIP/Temp_ASIP_one_one_tb_behav.wcfg -log simulate.log"
call xsim  ASIP_one_one_tb_behav -key {Behavioral:sim_1:Functional:ASIP_one_one_tb} -tclbatch ASIP_one_one_tb.tcl -view E:/codeDSIP_DoAn1/150425/Hardware_ASIP_14042025/Hardware_ASIP/Temp_ASIP_one_one_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
